# Generated by Django 5.0.1 on 2026-09-13 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicasAprender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa_album', models.ImageField(upload_to='')),
                ('nome_banda', models.CharField(max_length=40)),
                ('nome_musica', models.CharField(max_length=40)),
                ('duracao', models.IntegerField()),
                ('bpm', models.IntegerField()),
                ('instrumento', models.CharField(choices=[('Guitarra', 'Guitarra'), ('Violao', 'Violão')], default='Violao', max_length=8)),
            ],
            options={
                'verbose_name_plural': 'MusicasAprender',
            },
        ),
        migrations.CreateModel(
            name='MusicasAprendidas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('musica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cifras.musicasaprender')),
            ],
            options={
                'verbose_name_plural': 'MusicasAprendidas',
            },
        ),
    ]
