# Generated by Django 6.1 on 2026-09-17 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicasAprender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capa_album_small', models.ImageField(upload_to='')),
                ('capa_album_medium', models.ImageField(upload_to='')),
                ('nome_banda', models.CharField(max_length=40)),
                ('nome_musica', models.CharField(max_length=40)),
                ('duracao', models.IntegerField()),
                ('bpm', models.IntegerField()),
                ('instrumento', models.CharField(choices=[('Guitarra', 'Guitarra'), ('Violao', 'Violão')], default='Violao', max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='musicas_aprender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'MusicasAprender',
            },
        ),
        migrations.CreateModel(
            name='MusicasAprendidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('musica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='musicas_aprendidas', to='cifras.musicasaprender')),
            ],
            options={
                'verbose_name_plural': 'MusicasAprendidas',
            },
        ),
    ]
