# Generated by Django 6.1 on 2026-08-28 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicasAprender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_banda', models.CharField(max_length=40)),
                ('nome_musica', models.CharField(max_length=40)),
                ('duracao', models.TimeField()),
                ('tom_musica', models.CharField(max_length=5)),
                ('instrumento', models.CharField(choices=[('Guitarra', 'Guitarra'), ('Violao', 'Violão')], default='violao')),
            ],
            options={
                'verbose_name_plural': 'MusicasViolao',
            },
        ),
        migrations.CreateModel(
            name='Favorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('musica_favorita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cifras.musicasaprender')),
            ],
            options={
                'verbose_name_plural': 'Favoritas',
            },
        ),
    ]
