# Generated by Django 6.1 on 2026-09-01 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cifras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicasaprender',
            name='capa_album',
            field=models.ImageField(default='sadasdpaosdja', upload_to=''),
            preserve_default=False,
        ),
    ]
