# Generated by Django 6.1 on 2026-09-07 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cifras', '0002_musicasaprender_capa_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='MusicasAprendidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('musica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cifras.musicasaprender')),
            ],
            options={
                'verbose_name_plural': 'MusicasAprendidas',
            },
        ),
        migrations.DeleteModel(
            name='Favorita',
        ),
    ]
